apiVersion: v1
kind: Service
metadata:
  name: backendjuego1
spec:
  selector:
    app: backendjuego1
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
    nodePort: 30101
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendjuego1
spec:
  selector:
    matchLabels:
      app: backendjuego1
  replicas: 1
  template:
    metadata:
      labels:
        app: backendjuego1
    spec:
      containers:
      - name: backendjuego1
        image: docker.io/library/backendjuego1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080