apiVersion: v1
kind: Service
metadata:
  name: backendjuego
spec:
  selector:
    app: backendjuego
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
    nodePort: 30100
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendjuego
spec:
  selector:
    matchLabels:
      app: backendjuego
  replicas: 1
  template:
    metadata:
      labels:
        app: backendjuego
    spec:
      containers:
      - name: backendjuego
        image: mvxiandress/backendjuego
        ports:
        - containerPort: 8080