# Generated by Django 3.2.7 on 2021-10-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0002_auto_20211004_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='Resenha',
            new_name='Reseña',
        ),
    ]
