# Generated by Django 3.2.7 on 2021-10-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0003_rename_resenha_juego_reseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='Nombre',
            field=models.CharField(max_length=100),
        ),
    ]
