# Generated by Django 3.2.7 on 2021-10-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0004_alter_juego_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='Categoria',
            field=models.CharField(max_length=100),
        ),
    ]
